<?php
define('DBhost', 'localhost');
define('DBuser', 'root');
define('DBPass', '');
define('DBname', 'appartment_system');
define('APPLICATION_PATH',__DIR__);
try {
    $conn = new PDO("mysql:host=".DBhost.";dbname=".DBname,DBuser,DBPass);
    $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch(PDOException $e){
    die($e->getMessage());
}

function _d($var,$exit=0,$return=false){
	$print_text = "<pre style='font-size:8pt; background-color:#fff;color:#000;'>".print_r($var,1)."</pre><hr size=1 />";
	if($return) {
		return $print_text;
	}
	echo $print_text;
	if($exit) {
		exit;
	}
}

$url="";
if(stripos($_SERVER['SERVER_NAME'], "127.0") !==FALSE){
	$url="http://127.0.0.1/appartment_system/";
}elseif(stripos($_SERVER['SERVER_NAME'], "local.") !==FALSE){
	$url="http://localhost/appartment_system/";
}else{
	$url="http://".$_SERVER['SERVER_NAME']."/";
}

function get_ng_lgas() {
	return array(
		'Abia' => array(
			'Aba North',
			'Aba South',
			'Arochukwu',
			'Bende',
			'Ikwauano',
			'Isiala-Ngwa North',
			'Isiala-Ngwa South',
			'Isuikwuato',
			'Obi Ngwa',
			'Ohafia',
			'Osisioma Ngwa',
			'Ugwunagbo',
			'Ukwa East',
			'Ukwa West',
			'Umu Nneochi',
			'Umuahia North',
			'Umuahia South'
		),
		"Abuja" => array(
			"Abaji",
			"Abuja Municipal",
			"Bwari",
			"Gwagwalada",
			"Kuje",
			"Kwali"
		),
		"Adamawa" => array(
			"Demsa",
			"Fufore",
			"Ganye",
			"Girei",
			"Gombi",
			"Guyuk",
			"Hong",
			"Jada",
			"Lamurde",
			"Madagali",
			"Maiya",
			"Mayo",
			"Michika",
			"Mubi North",
			"Mubi South",
			"Numan",
			"Shelleg",
			"Song",
			"Toungo",
			"Yola",
			"Yola South"
		),
		"Akwa Ibom" => array(
			"Abak",
			"Eastern Obolo",
			"Eket",
			"Esit Eket",
			"Essien Udim",
			"Etim Ekpo",
			"Etinan",
			"Ibeno",
			"Ibesikpo Asutan",
			"Ibiono Ibom",
			"Ika",
			"Ikono",
			"Ikot Abasi",
			"Ikot Ekpene",
			"Ini",
			"Itu",
			"Mbo",
			"Mkpat Enin",
			"Nsit Atai",
			"Nsit Ibom",
			"Nsit Ubium",
			"Obot Akare",
			"Okobo",
			"Onna",
			"Oron",
			"Oruk Anam",
			"Udung Uko",
			"Ukanafun",
			"Uruan",
			"Urue/Offong",
			"Uyo"
		),
		"Anambra" => array(
			"Aguata",
			"Anambra East",
			"Anambra West",
			"Anaocha",
			"Awka North",
			"Awka South",
			"Ayamelum",
			"Dunukofia",
			"Ekwusigo",
			"Idemili North",
			"Idemili South",
			"Ihiala",
			"Njikoka",
			"Nnewi North",
			"Nnewi South",
			"Ogbaru",
			"Onitsha North",
			"Onitsha South",
			"Orumba North",
			"Orumba South",
			"Oyi"
		),
		"Bauchi" => array(
			"Alkaleri",
			"Bauchi",
			"Bogoro",
			"Dambam",
			"Darazo",
			"Dass",
			"Gamawa",
			"Ganjuwa",
			"Giade",
			"Itas-Gadau",
			"Jama'are",
			"Katagum",
			"Kirfi",
			"Misau",
			"Ningi",
			"Shira",
			"Tafawa Balewa",
			"Toro",
			"Warji",
			"Zaki"
		),
		"Bayelsa" => array(
			"Brass",
			"Ekeremor",
			"Kolokuma/Opokuma",
			"Nembe",
			"Ogbia",
			"Sagbama",
			"Southern Ijaw",
			"Yenagoa"
		),
		"Benue" => array(
			"Ado",
			"Agatu",
			"Apa",
			"Buruku",
			"Gboko",
			"Guma",
			"Gwer East",
			"Gwer West",
			"Katsina-Ala",
			"Konshisha",
			"Kwande",
			"Logo",
			"Markurdi",
			"Obi",
			"Ogbadibo",
			"Ohinimi",
			"Oju",
			"Okpokwu",
			"Otukpo",
			"Tarka",
			"Ukum",
			"Ushongo",
			"Vandeikya"
		),
		"Borno" => array(
			"Abadam",
			"Askira/Uba",
			"Bama",
			"Bayo",
			"Biu",
			"Chibok",
			"Damboa",
			"Dikwa",
			"Gubio",
			"Guzamala",
			"Gwoza",
			"Hawul",
			"Jere",
			"Kaga",
			"Kala Balge",
			"Konduga",
			"Kukawa",
			"Kwaya-Kusar",
			"Mafa",
			"Magumeri Gubio",
			"Maiduguri",
			"Marte",
			"Mobbar",
			"Monguno",
			"Ngala",
			"Nganzai",
			"Shani"
		),
		"Cross River" => array(
			"Abi",
			"Akamkpa",
			"Akpabuyo",
			"Bakassi",
			"Bekwara",
			"Biase",
			"Boki",
			"Calabar Municipal",
			"Calabar South",
			"Etung",
			"Ikom",
			"Obanliku",
			"Obubra",
			"Obudu",
			"Odukpani",
			"Ogoja",
			"Yakuur",
			"Yala"
		),
		"Delta" => array(
			"Aniocha North",
			"Aniocha South",
			"Bomadi",
			"Burutu",
			"Ethiope East",
			"Ethiope West",
			"Ika North East",
			"Ika South",
			"Isoko North",
			"Isoko South",
			"Ndokwa East",
			"Ndokwa West",
			"Okpe",
			"Oshimili North",
			"Oshimili South",
			"Patani",
			"Sapele",
			"Udu",
			"Ughelli North",
			"Ughelli South",
			"Ukwuani",
			"Uvwie",
			"Warri North",
			"Warri South",
			"Warri South West"
		),
		"Ebonyi" => array(
			"Abakaliki",
			"Afikpo North",
			"Afikpo South",
			"Ebonyi",
			"Ezza North",
			"Ezza South",
			"Ikwo",
			"Ishielu",
			"Ivo",
			"Izzi",
			"Ohaozara",
			"Ohaukwu",
			"Onicha"
		),
		"Edo" => array(
			"Akoko Edo",
			"Egor",
			"Esan Central",
			"Esan North East",
			"Esan South East",
			"Esan West",
			"Etsako Central",
			"Etsako East",
			"Etsako West",
			"Igueben",
			"Ikpoba-Okha",
			"Oredo",
			"Orhionmwon",
			"Ovia North-East",
			"Ovia South-West",
			"Owan East",
			"Owan West",
			"Uhunmwode"
		),
		"Ekiti" => array(
			"Ado Ekiti",
			"Efon",
			"Ekiti East",
			"Ekiti South West",
			"Ekiti West",
			"Emure",
			"Gbonyin",
			"Ido-Osi",
			"Ijero",
			"Ikere",
			"Ikole",
			"Ilejemeje",
			"Irepodun",
			"Ise Orun",
			"Moba",
			"Oye"
		),
		"Enugu" => array(
			"Aninri",
			"Awgu",
			"Enugu",
			"Ezeagu",
			"Igbo-Etiti",
			"Igbo-Eze North",
			"Igbo-Eze South",
			"Isi-Uzo",
			"Nkanu East",
			"Nkanu West",
			"Nsukka",
			"Oji River",
			"Udenu",
			"Udi",
			"Uzo-Uwani"
		),
		"Gombe" => array(
			"Akko",
			"Balanga",
			"Billiri",
			"Dukku",
			"Funakaye",
			"Gombe",
			"Kaltungo",
			"Kwami",
			"Nafada",
			"Shongom",
			"Yamaltu"
		),
		"Imo" => array(
			"Aboh-Mbaise",
			"Ahiazu-Mbaise",
			"Ehime-Mbano",
			"Ezinihitte",
			"Ideato North",
			"Ideato South",
			"Ihitte/Uboma",
			"Ikeduru",
			"Isiala Mbano",
			"Isu",
			"Mbaitoli",
			"Ngor-Okpala",
			"Njaba",
			"Nkwerre",
			"Nwangele",
			"Obowo",
			"Oguta",
			"Ohaji/Egbema",
			"Okigwe",
			"Onuimo",
			"Orlu",
			"Orsu",
			"Oru East",
			"Oru West",
			"Owerri",
			"Owerri North",
			"Owerri West"
		),
		"Jigawa" => array(
			"Auyo",
			"Babura",
			"Biriniwa",
			"Birnin Kudu",
			"Buji",
			"Dutse",
			"Gagarawa",
			"Garki",
			"Gumel",
			"Guri",
			"Gwaram",
			"Gwiwa",
			"Hadejia",
			"Jahun",
			"Kafin Hausa",
			"Kaugama",
			"Kazaure",
			"Kiri-Kasama",
			"Kiyawa",
			"Maigatari",
			"Malam-Madori",
			"Miga",
			"Ringim",
			"Roni",
			"Sule Tankarkar",
			"Taura",
			"Yankwashi"
		),
		"Kaduna" => array(
			"Birnin Gwari",
			"Chikun",
			"Giwa",
			"Igabi",
			"Ikara",
			"Jaba",
			"Jema'a",
			"Kachia",
			"Kaduna North",
			"Kaduna South",
			"Kagarko",
			"Kajuru",
			"Kaura",
			"Kauru",
			"Kubau",
			"Kudan",
			"Lere",
			"Makarfi",
			"Sabon Gari",
			"Sanga",
			"Soba",
			"Zangon Kataf",
			"Zaria"
		),
		"Kano" => array(
			"Ajingi",
			"Alabsu",
			"Bagwai",
			"Bebeji",
			"Bichi",
			"Bunkure",
			"Dala",
			"Dambatta",
			"Dawakin Kundu",
			"Dawakin Tofa",
			"Doguwa",
			"Fagge",
			"Gabasawa",
			"Garko",
			"Garun Mallam",
			"Gaya",
			"Gezawa",
			"Gwale",
			"Gwarzo",
			"Kabo",
			"Kano",
			"Karaye",
			"Kibiya",
			"Kiru",
			"Kumbotso",
			"Kunchi",
			"Kura",
			"Madobi",
			"Makoda",
			"Minjibir",
			"Nasarawa",
			"Rano",
			"Rimin Gado",
			"Rogo",
			"Shanono",
			"Sumaila",
			"Takai",
			"Tarauni",
			"Tofa",
			"Tsanyawa",
			"Tundun Wada",
			"Ungongo",
			"Warawa",
			"Wudil"
		),
		"Katsina" => array(
			"Bakori",
			"Batagarawa",
			"Batsari",
			"Baure",
			"Bindawa",
			"Charanchi",
			"Dan Musa",
			"Dandume",
			"Danja",
			"Daura",
			"Dutsi",
			"Dutsin Ma",
			"Faskari",
			"Funtua",
			"Ingawa",
			"Jibia",
			"Kafur",
			"Kaita",
			"Kankara",
			"Kankia",
			"Katsina",
			"Kurfi",
			"Kusada",
			"Mai'adua",
			"Malufashi",
			"Mani",
			"Mashi",
			"Matazu",
			"Musawa",
			"Rimi",
			"Sabuwa",
			"Safana",
			"Sandamu",
			"Zango"
		),
		"Kebbi" => array(
			"Aleiro",
			"Arewa Dandi",
			"Argungu",
			"Augie",
			"Bagudo",
			"Birni Kebbi",
			"Bunza",
			"Dandi",
			"Danko/Wasagu",
			"Fakai",
			"Gwandu",
			"Jega",
			"Kalgo",
			"Koko/Besse",
			"Maiyama",
			"Ngaski",
			"Sakaba",
			"Shanga",
			"Suru",
			"Yauri",
			"Zuru"
		),
		"Kogi" => array(
			"Adavi",
			"Ajaokuta",
			"Ankpa",
			"Bassa",
			"Dekina",
			"Ibaji",
			"Idah",
			"Igalamela-Odolu",
			"Ijumu",
			"Kabba/Bunu",
			"Kogi",
			"Lokoja",
			"Mopa-Muro",
			"Ofu",
			"Ogori/Magongo",
			"Okehi",
			"Okene",
			"Olamaboro",
			"Omala",
			"Yagba-East",
			"Yagba-West"
		),
		"Kwara" => array(
			"Asa",
			"Baruten",
			"Edu",
			"Ekiti",
			"Ifelodun",
			"Ilorin East",
			"Ilorin South",
			"Ilorin West",
			"Irepodun",
			"Isin",
			"Kaiama",
			"Moro",
			"Offa",
			"Oke Ero",
			"Oyun",
			"Pategi"
		),
		"Lagos" => array(
			"Agege/Ijaiye",
			"Ajeromi/Ifelodun",
			"Alimosho",
			"Amuwo Odofin",
			"Apapa",
			"Badagry",
			"Epe",
			"Eti Osa",
			"Ibeju/Lekki",
			"Ifako Ijaiye",
			"Ikeja",
			"Ikorodu",
			"Kosofe",
			"Lagos Island",
			"Lagos Mainland",
			"Mushin",
			"Ojo",
			"Oshodi/Isolo",
			"Shomolu",
			"Surulere"
		),
		"Nasarawa" => array(
			"Akwanga",
			"Awe",
			"Doma",
			"Karu",
			"Keana",
			"Keffi",
			"Kokona",
			"Lafia",
			"Nasarawa",
			"Nasarawa Egon",
			"Obi",
			"Toto",
			"Wamba"
		),
		"Niger" => array(
			"Agaie",
			"Agwara",
			"Bida",
			"Borgu",
			"Bosso",
			"Chanchaga",
			"Edati",
			"Gbako",
			"Gurara",
			"Katcha",
			"Kontagora",
			"Lapai",
			"Lavun",
			"Magama",
			"Mariga",
			"Mashegu",
			"Mokwa",
			"Munya",
			"Paikoro",
			"Raffi",
			"Rafi",
			"Rijau",
			"Shiroro",
			"Suleja",
			"Wushishi"
		),
		"Ogun" => array(
			"Abeokuta North",
			"Abeokuta South",
			"Ado Odo/Otta",
			"Egbado North",
			"Egbado South",
			"Ewekoro",
			"Ifo",
			"Ijebu East",
			"Ijebu North",
			"Ijebu North/East",
			"Ijebu Ode",
			"Ikenne",
			"Imeko Afon",
			"Ipokia",
			"Obafemi Owode",
			"Odeda",
			"Odogbolu",
			"Ogun Waterside",
			"Remo North",
			"Sagamu"
		),
		"Ondo" => array(
			"Akoko North East",
			"Akoko North West",
			"Akoko South East",
			"Akoko South West",
			"Akure North",
			"Akure South",
			"Ese Odo",
			"Idanre",
			"Ifedore",
			"Ilaje",
			"Ile Oluji",
			"Irele",
			"Odigbo",
			"Okitipupa",
			"Ondo East",
			"Ondo West",
			"Ose",
			"Owo"
		),
		"Osun" => array(
			"Aiyedaade",
			"Aiyedire",
			"Atakunmosa East",
			"Atakunmosa West",
			"Boluwaduro",
			"Boripe",
			"Ede North",
			"Ede South",
			"Egbedore",
			"Ejigbo",
			"Ife Central",
			"Ife East",
			"Ife North",
			"Ife South",
			"Ifedayo",
			"Ifelodun",
			"Ila",
			"Ilesa East",
			"Ilesa West",
			"Irepodun",
			"Irewole",
			"Isokan",
			"Iwo",
			"Obokun",
			"Odo Otin",
			"Ola Oluwa",
			"Olorunda",
			"Oriade",
			"Orolu",
			"Osogbo"
		),
		"Oyo" => array(
			"Afijio",
			"Akinyele",
			"Atiba",
			"Atisbo",
			"Egbeda",
			"Ibadan",
			"Ibarapa Central",
			"Ibarapa East",
			"Ibarapa North",
			"Ido",
			"Irepo",
			"Iseyin",
			"Itesiwaju",
			"Iwajowa",
			"Kajola",
			"Lagelu",
			"Ogbomosho",
			"Ogo Oluwa",
			"Olorunsogo",
			"Oluyole",
			"Ona-Ara",
			"Orelope",
			"Ori Ire",
			"Oyo East",
			"Oyo West",
			"Saki East",
			"Saki West",
			"South East",
			"South West",
			"Surulere"
		),
		"Plateau" => array(
			"Barkin Ladi",
			"Bassa",
			"Bokkos",
			"Jos East",
			"Jos North",
			"Jos South",
			"Kanam",
			"Kanke",
			"Langtang North",
			"Langtang South",
			"Mangu",
			"Mikang",
			"Pankshin",
			"Qua'an Pan",
			"Riyom",
			"Shendam",
			"Wase"
		),
		"Rivers" => array(
			"Abua/Odual",
			"Ahoada East",
			"Ahoada West",
			"Akuku Toru",
			"Andoni",
			"Asari Toru",
			"Bonny",
			"Degema",
			"Eleme",
			"Emohua",
			"Etche",
			"Gokana",
			"Ikwerre",
			"Khana",
			"Obio/Akpor",
			"Ogba",
			"Ogubolo",
			"Okrika",
			"Omuma",
			"Opobo Nkoro",
			"Oyigbo",
			"Port Harcourt",
			"Tai"
		),
		"Sokoto" => array(
			"Binji",
			"Bodinga",
			"Dange-Shuni",
			"Gada",
			"Gonroyo",
			"Gudu",
			"Gwadabawa",
			"Illela",
			"Isa",
			"Kebbe",
			"Kware",
			"Sabon Birni",
			"Shagari",
			"Silame",
			"Sokoto North",
			"Sokoto South",
			"Tambuwal",
			"Tangaza",
			"Tureta",
			"Wamako",
			"Wurno",
			"Yabo"
		),
		"Taraba" => array(
			"Ardo Kola",
			"Bali",
			"Donga",
			"Gashaka",
			"Gassol",
			"Ibi",
			"Jalingo",
			"Karim Lamido",
			"Kurmi",
			"Lau",
			"Sardauna",
			"Takum",
			"Ussa",
			"Wukari",
			"Yorro",
			"Zing"
		),
		"Yobe" => array(
			"Bade",
			"Bursari",
			"Damaturu",
			"Fika",
			"Fune",
			"Geidam",
			"Gujba",
			"Gulani",
			"Jakusko",
			"Karasuwa",
			"Machina",
			"Nangere",
			"Nguru",
			"Potiskum",
			"Tarmuwa",
			"Yunusari",
			"Yusufari"
		),
		"Zamfara" => array(
			"Anka",
			"Bakura",
			"Birni Magaji/Kiyaw",
			"Bukkuyum",
			"Bungudu",
			"Chafe",
			"Gummi",
			"Gusau",
			"Kaura Namoda",
			"Maradun",
			"Maru",
			"Shinkafi",
			"Talata Mafara",
			"Zurmi"
		)
	);
}